[ERROR] 2022-06-14 00:47:04,915 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/membership_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:06,596 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/volunteer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:08,356 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/volunteer_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:15,079 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/certification_application'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:17,099 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/certified_consultant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:18,938 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/chapter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:22,408 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/donor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:24,052 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/donor_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:25,489 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/grant_application'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:32,363 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/certified_consultant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:36,323 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/volunteer_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:40,623 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/membership'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 00:47:46,385 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/non_profit/doctype/certification_application'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
