[ERROR] 2022-06-14 01:03:29,559 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "cmd": "frappe.desk.query_report.run",
 "filters": "{}",
 "report_name": "General Ledger"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 548, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 213, in run
    result = generate_report_result(report, filters, user, custom_columns)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 548, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 73, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 57, in get_report_result
    res = report.execute_script_report(filters)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 120, in execute_script_report
    res = self.execute_module(filters)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 137, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1096, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 870, in get_module
    return importlib.import_module(modulename)
  File "/home/ubuntu/frappe-bench/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext.accounts.report.general_ledger'
[ERROR] 2022-06-14 01:03:29,758 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2022-06-14 01:03:29.566709-127.0.0.1-a8c
[ERROR] 2022-06-14 01:05:46,726 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "cached_timestamp": "2018-03-08 10:47:32.830478",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Payment Term",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_term'
[ERROR] 2022-06-14 01:05:46,849 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_term'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 01:05:49,307 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "cached_timestamp": "2018-03-08 10:47:32.830478",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Payment Term",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_term'
[ERROR] 2022-06-14 01:05:49,315 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_term'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 01:05:55,995 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "cached_timestamp": "",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Sales Invoice",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 97, in add_code
    self._add_code(_get_path(self.name + '.js'), '__js')
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 120, in _add_code
    js = get_js(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 245, in get_js
    return render_include(js)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/utils/__init__.py", line 70, in render_include
    with io.open(frappe.get_app_path(app, app_path), 'r', encoding = 'utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/selling/sales_common.js'
[ERROR] 2022-06-14 01:05:55,997 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 97, in add_code
    self._add_code(_get_path(self.name + '.js'), '__js')
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 120, in _add_code
    js = get_js(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 245, in get_js
    return render_include(js)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/utils/__init__.py", line 70, in render_include
    with io.open(frappe.get_app_path(app, app_path), 'r', encoding = 'utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/selling/sales_common.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 01:06:53,841 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "cached_timestamp": "2018-08-29 06:37:19.908254",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Currency",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/frappe/frappe/geo/doctype/currency'
[ERROR] 2022-06-14 01:06:53,851 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/frappe/frappe/geo/doctype/currency'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 01:06:56,437 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "cached_timestamp": "2018-08-29 06:37:19.908254",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Currency",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/frappe/frappe/geo/doctype/currency'
[ERROR] 2022-06-14 01:06:56,449 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 117, in add_code
    self.add_html_templates(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 129, in add_html_templates
    for fname in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/frappe/frappe/geo/doctype/currency'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
[ERROR] 2022-06-14 01:06:57,685 | /home/ubuntu/frappe-bench/apps/frappe/frappe/app.py:
Site: proveedor_orden
Form Dict: {
 "cached_timestamp": "",
 "cmd": "frappe.desk.form.load.getdoctype",
 "doctype": "Sales Invoice",
 "with_parent": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 97, in add_code
    self._add_code(_get_path(self.name + '.js'), '__js')
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 120, in _add_code
    js = get_js(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 245, in get_js
    return render_include(js)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/utils/__init__.py", line 70, in render_include
    with io.open(frappe.get_app_path(app, app_path), 'r', encoding = 'utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/selling/sales_common.js'
[ERROR] 2022-06-14 01:06:57,688 | /home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1105, in call
    return fn(*args, **newargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 70, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 37, in get_meta
    meta = FormMeta(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 47, in __init__
    self.load_assets()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 63, in load_assets
    self.add_code()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 97, in add_code
    self._add_code(_get_path(self.name + '.js'), '__js')
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 120, in _add_code
    js = get_js(path)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 245, in get_js
    return render_include(js)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/utils/__init__.py", line 70, in render_include
    with io.open(frappe.get_app_path(app, app_path), 'r', encoding = 'utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/frappe-bench/apps/erpnext/erpnext/selling/sales_common.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
